import org.junit.Test;
import static org.junit.Assert.*;
import com.metadetron.camel.Camel01;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'cracoviano' at '12/19/15 1:08 PM' with Gradle 2.8
 *
 * @author cracoviano, @date 12/19/15 1:08 PM
 */
public class Camel01Test {
    @Test public void testMain() {

    	try {
        	Camel01.main(new String[] {});
	        assertTrue("Test OK", true);
        } catch (Exception e) {
        	System.out.println("Exception: " + e.getMessage());
        	assertTrue("Exception: " + e.getMessage(), true);
        }
    }
}
